/*
 * Copyright (c) 2024 TECH VEDA(www.techveda.org)
 * Author: Raghu Bharadwaj
 * This software is dual-licensed under the MIT License and GPL v2.
 * See the accompanying LICENSE file for the full text.
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/notifier.h>
#include <linux/kthread.h>
#include <linux/delay.h>

/* Custom events */
#define CUSTOM_EVENT_START    1
#define CUSTOM_EVENT_WORK     2  
#define CUSTOM_EVENT_STOP     3

/*
 * What triggers this notifier?
 * - Custom RAW notifier events generated by this module's kthread.
 *   Sequence per cycle: CUSTOM_EVENT_START → CUSTOM_EVENT_WORK → CUSTOM_EVENT_STOP
 * - Events are dispatched via raw_notifier_call_chain() every few seconds.
 */

static RAW_NOTIFIER_HEAD(custom_notifier_list);
static struct task_struct *event_generator_thread;
static int event_count = 0;

/* First notifier callback - high priority */
static int high_priority_callback(struct notifier_block *nb, unsigned long event, void *data)
{
    int *counter = (int *)data;
    
    switch (event) {
    case CUSTOM_EVENT_START:
        pr_info("%s: HIGH_PRIORITY - Start event detected (data: %d)\n", 
                __func__, *counter);
        break;
    case CUSTOM_EVENT_WORK:
        pr_info("%s: HIGH_PRIORITY - Work event detected (data: %d)\n", 
                __func__, *counter);
        break;
    case CUSTOM_EVENT_STOP:
        pr_info("%s: HIGH_PRIORITY - Stop event detected (data: %d)\n", 
                __func__, *counter);
        break;
    }
    
    return NOTIFY_OK;
}

/* Second notifier callback - medium priority */
static int medium_priority_callback(struct notifier_block *nb, unsigned long event, void *data)
{
    int *counter = (int *)data;
    
    switch (event) {
    case CUSTOM_EVENT_START:
        pr_info("%s: MEDIUM_PRIORITY - Processing start (data: %d)\n", 
                __func__, *counter);
        break;
    case CUSTOM_EVENT_WORK:
        pr_info("%s: MEDIUM_PRIORITY - Processing work (data: %d)\n", 
                __func__, *counter);
        break;
    case CUSTOM_EVENT_STOP:
        pr_info("%s: MEDIUM_PRIORITY - Processing stop (data: %d)\n", 
                __func__, *counter);
        break;
    }
    
    return NOTIFY_OK;
}

/* Third notifier callback - low priority */
static int low_priority_callback(struct notifier_block *nb, unsigned long event, void *data)
{
    int *counter = (int *)data;
    
    switch (event) {
    case CUSTOM_EVENT_START:
        pr_info("%s: LOW_PRIORITY - Final start processing (data: %d)\n", 
                __func__, *counter);
        break;
    case CUSTOM_EVENT_WORK:
        pr_info("%s: LOW_PRIORITY - Final work processing (data: %d)\n", 
                __func__, *counter);
        break;
    case CUSTOM_EVENT_STOP:
        pr_info("%s: LOW_PRIORITY - Final stop processing (data: %d)\n", 
                __func__, *counter);
        break;
    }
    
    return NOTIFY_OK;
}

static struct notifier_block high_priority_nb = {
    .notifier_call = high_priority_callback,
    .priority = 100,  /* Highest priority */
};

static struct notifier_block medium_priority_nb = {
    .notifier_call = medium_priority_callback,
    .priority = 50,   /* Medium priority */
};

static struct notifier_block low_priority_nb = {
    .notifier_call = low_priority_callback,
    .priority = 0,    /* Lowest priority */
};

static int event_generator_fn(void *data)
{
    int i;
    
    pr_info("%s: Event generator thread started\n", __func__);
    
    for (i = 1; i <= 10 && !kthread_should_stop(); i++) {
        event_count = i;
        
        pr_info("%s: === Generating event cycle %d ===\n", __func__, i);
        
        /* Generate START event */
        raw_notifier_call_chain(&custom_notifier_list, CUSTOM_EVENT_START, &event_count);
        msleep(1000);
        
        /* Generate WORK event */
        raw_notifier_call_chain(&custom_notifier_list, CUSTOM_EVENT_WORK, &event_count);
        msleep(1000);
        
        /* Generate STOP event */
        raw_notifier_call_chain(&custom_notifier_list, CUSTOM_EVENT_STOP, &event_count);
        msleep(2000);
    }
    
    pr_info("%s: Event generator thread exiting\n", __func__);
    return 0;
}

static int __init custom_notifier_init(void)
{
    int ret;
    
    pr_info("%s: Custom notifier chain module loaded\n", __func__);
    
    /* Register notifiers in reverse priority order to demonstrate ordering */
    ret = raw_notifier_chain_register(&custom_notifier_list, &low_priority_nb);
    if (ret) {
        pr_err("%s: Failed to register low priority notifier\n", __func__);
        return ret;
    }
    
    ret = raw_notifier_chain_register(&custom_notifier_list, &medium_priority_nb);
    if (ret) {
        pr_err("%s: Failed to register medium priority notifier\n", __func__);
        goto unregister_low;
    }
    
    ret = raw_notifier_chain_register(&custom_notifier_list, &high_priority_nb);
    if (ret) {
        pr_err("%s: Failed to register high priority notifier\n", __func__);
        goto unregister_medium;
    }
    
    /* Start event generator thread */
    event_generator_thread = kthread_run(event_generator_fn, NULL, "custom_events");
    if (IS_ERR(event_generator_thread)) {
        pr_err("%s: Failed to create event generator thread\n", __func__);
        ret = PTR_ERR(event_generator_thread);
        goto unregister_high;
    }
    
    pr_info("%s: Custom notifier chain initialized successfully\n", __func__);
    return 0;
    
unregister_high:
    raw_notifier_chain_unregister(&custom_notifier_list, &high_priority_nb);
unregister_medium:
    raw_notifier_chain_unregister(&custom_notifier_list, &medium_priority_nb);
unregister_low:
    raw_notifier_chain_unregister(&custom_notifier_list, &low_priority_nb);
    return ret;
}

static void __exit custom_notifier_exit(void)
{
    if (event_generator_thread)
        kthread_stop(event_generator_thread);
    
    raw_notifier_chain_unregister(&custom_notifier_list, &high_priority_nb);
    raw_notifier_chain_unregister(&custom_notifier_list, &medium_priority_nb);
    raw_notifier_chain_unregister(&custom_notifier_list, &low_priority_nb);
    
    pr_info("%s: Custom notifier chain module unloaded\n", __func__);
}

module_init(custom_notifier_init);
module_exit(custom_notifier_exit);

MODULE_LICENSE("Dual MIT/GPL");
MODULE_AUTHOR("Raghu Bharadwaj");
MODULE_DESCRIPTION("Custom notifier chain demonstration");
MODULE_VERSION("1.0");
